apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-app
  template:
    metadata:
      labels:
        app: rag-app
    spec:
      containers:
      - name: rag-app
        image: 148617059235.dkr.ecr.us-east-1.amazonaws.com/ai-code-review-agent:latest
        ports:
        - containerPort: 8051
---
apiVersion: v1
kind: Service
metadata:
  name: rag-service
spec:
  selector:
    app: rag-app
  ports:
  - port: 8051
    targetPort: 8051
  type: NodePort